import type {
  AvailabilityFlagId,
  DetailedPosition,
  RangeId,
  RoleId,
  SortId,
  TrialNoteId,
} from "../../data/types.ts";
import { plural } from "./polish-format.ts";

function formatAge(years: number): string {
  return `${years} ${plural(years, "rok", "lata", "lat")}`;
}

export const LIST_TEXT = {
  autoFill: "Dobierz losowo",
  clearSquad: "Odwołaj wszystkich",
  newGame: "Nowa gra",
  roles: {
    aerial: "Powietrze",
    ballPlaying: "Gra nogami",
    ballWinning: "Odbiór",
    boxPresence: "Pole karne",
    buildUp: "Wyprowadzenie",
    centreBack: "Stoper",
    dribbling: "Drybling",
    experience: "Weteran",
    leader: "Lider",
    leftFoot: "Lewa noga",
    linkUp: "Łączenie gry",
    longShots: "Strzał z dystansu",
    pace: "Szybkość",
    playmaker: "Kreator",
    potential: "Potencjał",
    pressing: "Pressing",
    reach: "Zasięg",
    reflexes: "Refleks",
    rightBack: "Gra na boku",
    setPieces: "Stałe fragmenty",
    striker: "Wykończenie",
    winger: "Skrzydło",
    wingBack: "Wahadło",
  } satisfies Record<RoleId, string>,
  availabilityFlags: {
    injuryRisk: "Ryzyko urazu",
    minutesLimit: "Limit minut",
  } satisfies Record<AvailabilityFlagId, string>,
  kpis: { quality: "Jakość", fit: "Dopasowanie", risk: "Ryzyko zdrowotne" },
  facts: { term: "Termin", formation: "Formacja" },
  risk: { none: "Brak", low: "Niskie", medium: "Średnie", high: "Wysokie" },
  emptyValue: "Brak",
  searchPlaceholder: "Szukaj zawodnika lub klubu…",
  searchLabel: "Szukaj zawodnika",
  positionChipsLabel: "Filtry pozycyjne (wybrani/dostępni):",
  chip: (code: string, picked: number, total: number) =>
    `${code} (${picked}/${total})`,
  chipName: (code: string, picked: number, total: number, name: string) =>
    `${code} (${picked}/${total}): ${name}, powołani ${picked} z ${total}`,
  chipAllName: (picked: number, total: number) =>
    `Wszyscy (${picked}/${total}): powołani ${picked} z ${total}`,
  detailFilters: "Filtry szczegółowe",
  detailFiltersActive: (count: number) =>
    `Filtry szczegółowe, aktywne: ${count}`,
  skipToList: "Przejdź do listy kandydatów",
  footLegend: "Noga wiodąca",
  footLeft: "Lewa noga",
  footRight: "Prawa noga",
  footHint: "Zaznacz obie, aby pokazać obunożnych.",
  traitsLegend: "Cechy",
  rangesLegend: "Zakresy",
  ranges: {
    age: "Wiek",
    score: "Ocena selekcyjna",
    quality: "Jakość",
    form: "Forma",
    fitness: "Zdrowie",
    tactics: "Taktyka",
    experience: "Doświadczenie",
    chemistry: "Zgranie kadrowe",
    groupImpact: "Wpływ na grupę",
    campImpact: "Wynik zgrupowania",
  } satisfies Record<RangeId, string>,
  rangeFrom: (label: string) => `${label} od`,
  rangeTo: (label: string) => `${label} do`,
  clearFilters: "Wyczyść filtry",
  sortVisibleLabel: "Sortuj:",
  visibleCount: (count: number, total: number) =>
    `Widoczni: ${count} z ${total}`,
  onlyGroupLabel: "Pokaż tylko",
  onlySelected: (count: number) => `Tylko powołani (${count})`,
  onlyCamp: (count: number) => `Tylko z marcowego zgrupowania (${count})`,
  allCandidates: "Wszyscy kandydaci",
  noCandidates: "Brak zawodników spełniających kryteria.",
  noCandidatesHint:
    "Wyczyść wyszukiwanie albo filtry, aby zobaczyć więcej kandydatów.",
  sort: {
    model: "Ocena selekcyjna",
    quality: "Jakość",
    form: "Forma",
    fitness: "Zdrowie",
    tactics: "Taktyka",
    experience: "Doświadczenie",
    group: "Wpływ na grupę",
    young: "Wiek: najmłodsi",
    old: "Wiek: najstarsi",
    name: "Nazwisko A–Z",
  } satisfies Record<SortId, string>,
  positions: {
    BR: "Bramkarz",
    LO: "Lewy obrońca",
    LŚO: "Lewy środkowy obrońca",
    ŚO: "Środkowy obrońca",
    PŚO: "Prawy środkowy obrońca",
    PO: "Prawy obrońca",
    LWO: "Lewy wahadłowy",
    DP: "Defensywny pomocnik",
    ŚP: "Środkowy pomocnik",
    OP: "Ofensywny pomocnik",
    PWO: "Prawy wahadłowy",
    LS: "Lewe skrzydło",
    N: "Napastnik",
    PS: "Prawe skrzydło",
  } satisfies Record<DetailedPosition, string>,
  filtersAll: "Wszyscy",
  select: "Powołaj",
  selected: "Powołany ✓",
  selectedName: "Powołany",
  profile: "Profil",
  compare: "Porównaj",
  compared: "Wybrany",
  playerAction: (label: string, name: string) => `${label}: ${name}`,
  // codes and names arrive joined with ", "; the names read lowercase inside the sentence
  positionBadgeName: (codes: string, names: string) =>
    `${codes}: ${`${names}`.toLocaleLowerCase("pl")}`,
  positionPopoverSeparator: " · ",
  positionMore: (count: number) => `+${count}`,
  playerMetrics: {
    quality: "Jakość",
    form: "Forma",
    fitness: "Zdrowie",
    tactics: "Taktyka",
  },
  selectionScore: "Ocena selekcyjna",
  age: formatAge,
  campResult: "Zgrupowanie",
  trialNotes: {
    impressed: "przekonał",
    solid: "bez zarzutu",
    uncertain: "niepewny",
    disappointed: "rozczarował",
  } satisfies Record<TrialNoteId, string>,
  foot: {
    both: "Obunożny",
    left: "Lewa",
    right: "Prawa",
    lead: "Wiodąca noga:",
  },
} as const;
