// Shared Git hook logic for people, Codex and Claude Code. Invoked by .githooks/*.
// Usage: node scripts/git-hooks.mjs pre-commit
//        node scripts/git-hooks.mjs commit-msg <message-file>
import { execFileSync, spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";

// Commits may be authored by the owner under any identity, but never by an AI tool.
const AI_IDENTITY =
  /\b(codex|chatgpt|openai|claude|anthropic|copilot|gemini|cursor|devin|aider)\b/i;
const AI_ATTRIBUTION = [
  /^co-authored-by:.*\b(codex|chatgpt|openai|claude|anthropic|copilot|gemini|cursor|devin|aider)\b/im,
  /generated (with|by) .*(codex|chatgpt|openai|claude|anthropic|copilot|gemini|cursor)/i,
  /^(claude|codex|openai|anthropic)[\w-]*:/im,
];
const EMOJI = /\p{Emoji_Presentation}/u;
const CONVENTIONAL =
  /^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?!?: \S/;

function fail(message) {
  process.stderr.write(`\n[git hook] ${message}\n\n`);
  process.exit(1);
}

function git(args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

function preCommit() {
  for (const role of ["GIT_AUTHOR_IDENT", "GIT_COMMITTER_IDENT"]) {
    const identity = git(["var", role]).replace(/\s+\d+\s+[+-]\d{4}$/, "");
    if (AI_IDENTITY.test(identity))
      fail(
        `${role} is "${identity}". Commits must use the owner's identity, never an AI tool's.`,
      );
  }
  const whitespace = spawnSync("git", ["diff", "--cached", "--check"], {
    stdio: "inherit",
  });
  if (whitespace.status !== 0) fail("Whitespace errors in staged changes.");
  const staged = git([
    "diff",
    "--cached",
    "--name-only",
    "--diff-filter=ACMR",
    "-z",
  ])
    .split("\0")
    .filter(Boolean);
  if (staged.some((file) => file.startsWith("dist/")))
    fail("dist/ is generated by `pnpm build`; do not commit it here.");
  if (staged.length === 0) return;
  const text = spawnSync(
    process.execPath,
    ["scripts/check-text.mjs", ...staged],
    { stdio: "inherit" },
  );
  if (text.status !== 0) fail("Staged files contain forbidden characters.");
  const conventions = spawnSync(
    process.execPath,
    ["scripts/check-conventions.mjs"],
    { stdio: "inherit" },
  );
  if (conventions.status !== 0) fail("Repository conventions are violated.");
}

function commitMsg(file) {
  const message = readFileSync(file, "utf8")
    .split("\n")
    .filter((line) => !line.startsWith("#"))
    .join("\n")
    .trim();
  const subject = message.split("\n")[0] ?? "";
  if (/^(Merge|Revert) /.test(subject) || /^(fixup|squash)! /.test(subject))
    return;
  if (!CONVENTIONAL.test(subject))
    fail(
      `Subject "${subject}" is not a Conventional Commit, e.g. "fix(storage): report failed saves".`,
    );
  if (subject.length > 72)
    fail(`Subject is ${subject.length} characters; keep it at 72 or fewer.`);
  if (AI_ATTRIBUTION.some((pattern) => pattern.test(message)))
    fail("Remove AI authorship or attribution lines from the commit message.");
  if (EMOJI.test(message)) fail("Remove emoji from the commit message.");
}

const [hook, argument] = process.argv.slice(2);
if (hook === "pre-commit") preCommit();
else if (hook === "commit-msg" && argument) commitMsg(argument);
else fail(`Unknown hook invocation: ${process.argv.slice(2).join(" ")}`);
